- import_playbook: tasks/ssh.yml
- import_playbook: tasks/set-defaults.yml
- import_playbook: tasks/homebrew.yml
- import_playbook: tasks/dotfiles.yml
- import_playbook: tasks/zsh.yml
- import_playbook: tasks/nvim-setup.yml
- import_playbook: tasks/rust.yml
- import_playbook: tasks/fnm.yml
- import_playbook: tasks/asdf.yml
