- hosts: localhost
  become: false 
  vars:
    golang_version: 1.21.0
    elixir_version: 1.14.5-otp-25
    erlang_version: 25.3.2.2
  tasks:
    - name: Install golang
      shell: asdf install golang {{ golang_version }}
      tags:
        - install
        - asdf
    - name: Setup golang global
      shell: asdf global golang {{ golang_version }}
      tags:
        - install
        - asdf
    - name: Install erlang
      shell: asdf install erlang {{ erlang_version }}
      tags:
        - install
        - asdf
    - name: Setup erlang global
      shell: asdf global erlang {{ erlang_version }}
      tags:
        - install
        - asdf
    - name: Install elixir
      shell: asdf install elixir {{ elixir_version }}
      tags:
        - install
        - asdf
    - name: Setup elixir global
      shell: asdf global elixir {{ elixir_version }}
      tags:
        - install
        - asdf
