- hosts: localhost
  become: false
  vars:
    brew_tap_modules:
      - homebrew/cask-fonts
    brew_cask_packages:
      - font-jetbrains-mono
      - homebrew/cask-fonts/font-fira-code
      - homebrew/cask-fonts/font-inconsolata-g
      - homebrew/cask-fonts/font-inconsolata-g-for-powerline
    brew_packages:
      - autojump
      - the_silver_searcher
      - tmux
      - neovim
      - fzf
      - autoconf
      - automake
      - ca-certificates
      - consul
      - consul-template
      - coreutils
      - ffmpeg
      - imagemagick
      - jless
      - jq
      - magic-wormhole
      - mysql-client
      - nomad
      - stow
      - tfenv
      - asdf
      - gcc
      - vault
      - vips
      - wget
      - parallel
      - graphviz
      - pkg-config
      - fnm
      - cmake
      - jrnl
    install_homebrew_if_missing: true
    upgrade_homebrew_packages: false
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing
    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists
      tags:
        - homebrew

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
      tags:
        - homebrew

    - name: Tap Homebrew Modules
      homebrew_tap:
        name: "{{ brew_tap_modules }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
      tags:
        - homebrew

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
      tags:
        - homebrew

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
      tags:
        - homebrew
