- hosts: localhost
  become: false
  tasks:
  - name: Clone tpm (Tmux Plugin Manager)
    ansible.builtin.git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    tags:
      - install
      - tmux
