- hosts: localhost
  become: true
  vars:
    source_key: "../.zsh/.zshrc-private"
    dest_key: "{{ lookup('env', 'HOME') }}/.zshrc-private"
  tasks:
    - name: Copy zshrc-private
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        owner: gianu
        group: staff
        mode: 0644
      tags:
        - dotfiles
        - install
        - zsh
